### ISSUE TITLE
Unable to create higher tier custom vision project

### ISSUE THREAD

**Issue by NiChloride** [sw6y15/HKEvent#12]
Hi!

We made a custom vision service on azure portal using S0 pricing option, but we can not create projects for it on the custom vision portal itself. Could you please explain how to do that?

**Comment by sw6y15** [comment]
Make sure resource group is the S0 service you made in azure portal but **NOT** choose limit trial:

![image](https://user-images.githubusercontent.com/29120664/51298831-22d44f80-1a61-11e9-9b0e-ab0eb72d3de6.png)
Cuz it only allows you to create 2 projects on limit trial.

And you can check which resource group of the project by looking at label under project name.

![image](https://user-images.githubusercontent.com/29120664/51298988-b60d8500-1a61-11e9-8195-b02121a3ec2d.png)
