### ISSUE TITLE
I have an Nividia card, how do I build darknet with GPU?

### ISSUE THREAD

**Issue by NiChloride** [sw6y15/HKEvent#13]
Do I simply follow the same steps for the no_gpu version just instead with darknet.sln?

**Comment by sw6y15** [comment]
If you want to use darknet, I suggest to use darknet.sln due to no_gpu version is too slow to train a model. You can follow slides of S4 provide in the course or refer this [page](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows) to build with GPU.
