### ISSUE TITLE
Exported onnx failed

### ISSUE THREAD

**Issue by HeidiZHH** [sw6y15/HKEvent#15]
We tried to download the onnx file from the Microsoft custom vision service. However, when we tried to use the model with sample code from session3 of the workshop, we could not get a similar output as we got from the quick test function on the Custom Vision. Moreover, we tried to test our model by directly include the prediction key in the sample code from session2, it works. I was wondering if we did anything wrong when export our model to onnx. 
Thank you.

**Comment by LiangJy123** [comment]
With the sample code from session3 ,you can see at the 50th line in the file called ”ProcessWithONNX.cs“.
Try to modify the last two parameters, maybe you can get what you want.
  ```
  objectDetection = new ObjectDetection(labels, 20, 0.4F, 0.45F);
 ```

![image](https://user-images.githubusercontent.com/13048899/51318646-dc4d1800-1a95-11e9-96b5-1b081afdbaed.png)

**Comment by HeidiZHH** [comment]
We've tried it and that's what we encounter: with the exact same photo. The model was able to detect the object with reasonable probability(e.g. over 80%). However, if we export it as onnx and use it in the sample code, even if we tune the threshold to 0.0, it would display like many meaningless squares with figures like 0.00x probability with it or is this totally normal when we are doing AI model training?

**Comment by LiangJy123** [comment]
Are you saying that your onnx can't find the object correctly?
Confirm if you have changed the file called "ObjectDetection.cs".
Because it contains parsing data, if it is incorrect, the data will be misplaced and may cause your problems.
