### ISSUE TITLE
Darknet Weights Not Works

### ISSUE THREAD

**Issue by Chiaki530** [sw6y15/HKEvent#4]
**Describe the bug**
We use the three given images(apple, banana, apple & banana) to train the darknet model using tiny-yolo-voc.cfg. When using our final weights to predict, we cannot see any predictions. However, if we use the given sample weights to predict, there are too many (more than 50). 

**Expected behavior**
Each object has only one description. 

**Desktop (please complete the following information):**
Win10 

**Attend date**
08/01/2019

**Additional context**

**Comment by sw6y15** [comment]
Could you give us which command you use or provide the screenshot of your prediction. 
I'm notice that you only use three images to train. Cuz they are only the example of how to use VoTT to tag images. If you'd like to make a acceptable detection, I'm afraid you should take or download more images to tag and train. The sample weight **tiny-yolo-voc.weights**  is a 20-classes classification model. And it is also a sample to show how to use darknet.
