### ISSUE TITLE
Problem with converting weights to ONNX

### ISSUE THREAD

**Issue by jhl8041** [sw6y15/HKEvent#5]
**Describe the bug**
Model ONNX file is not generated with the errors shown below:
_IOError: Unable to open file (unable to open file: name = 'yad2k/model_data/tiny-yolo-voc.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Generated Coreml file.
WARNING:root:TensorFlow version 1.12.0 detected. Last version known to be fully compatible is 1.5.0 .
Traceback (most recent call last):
  File "coreml2onnx", line 4, in <module>
    coreml_model = coremltools.utils.load_spec('TinyYOLO.mlmodel')
  File "/usr/local/lib/python2.7/dist-packages/coremltools/models/utils.py", line 90, in load_spec
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'TinyYOLO.mlmodel'
Generated onnx file_

**To Reproduce**
1. Open Ubuntu
2. cd YOLO-CoreML-MPSNNGraph
3. sudo bash Darknet2ONNX.sh example.cfg example.weights

**Expected behavior**
It should generate 'model.onnx' file at: USERFILE%/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_*/LocalState/rootfs/home/${wsl_user_name}/YOLO-CoreML-MPSNNGraph/ TinyYOLO-CoreML/TinyYOLO-CoreML/model.onnx

**Screenshots**
![image](https://user-images.githubusercontent.com/39699436/51071980-a7efeb00-1694-11e9-9648-f163a787e26c.png)

![image](https://user-images.githubusercontent.com/39699436/51071916-d3bea100-1693-11e9-969f-7bd03fe0837c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 and using Ubuntu 18.04

**Attend date**
11/01/2019

**Additional context**
We also had errors of unable to find 'keras' and 'tensorflow' module and we have solved it by using [pip3 install keras], and [pip3 install tensorflow==1.5.0]. However, could not solve IOError.

**Comment by jhl8041** [comment]
I ran following commands:

**pip install Keras==1.2.2
pip3 install Keras==1.2.2**

Then, I tried to convert using **tiny-yolo-voc.cfg** and the given sample weight **tiny-yolo-voc.weights** but it is showing the same problem

**Running pip list:**
absl-py (0.6.1)
asn1crypto (0.24.0)
astor (0.7.1)
backports.weakref (1.0.post1)
bleach (1.5.0)
coremltools (2.0)
cryptography (2.1.4)
enum34 (1.1.6)
funcsigs (1.0.2)
futures (3.2.0)
gast (0.2.1.post0)
grpcio (1.17.1)
h5py (2.9.0)
html5lib (0.9999999)
idna (2.6)
ipaddress (1.0.17)
Keras (1.2.2)
Keras-Applications (1.0.6)
Keras-Preprocessing (1.0.5)
keyring (10.6.0)
keyrings.alt (3.0)
Markdown (3.0.1)
mock (2.0.0)
numpy (1.15.4)
onnx (1.3.0)
onnxmltools (1.3.1)
pbr (5.1.1)
pip (9.0.1)
protobuf (3.6.1)
pycrypto (2.6.1)
pygobject (3.26.1)
pyxdg (0.25)
PyYAML (3.13)
scipy (1.2.0)
SecretStorage (2.3.1)
setuptools (40.6.3)
six (1.12.0)
tensorboard (1.12.2)
tensorflow (1.5.0)
tensorflow-tensorboard (1.5.1)
termcolor (1.1.0)
Theano (1.0.3)
typing (3.6.6)
typing-extensions (3.6.6)
Werkzeug (0.14.1)
wheel (0.32.3)

**Running pip3 list:** 
absl-py (0.6.1)
asn1crypto (0.24.0)
astor (0.7.1)
attrs (17.4.0)
Automat (0.6.0)
bleach (1.5.0)
blinker (1.4)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
cloud-init (18.2)
colorama (0.3.7)
command-not-found (0.3)
configobj (5.0.6)
constantly (15.1.0)
cryptography (2.1.4)
distro-info (0.18)
gast (0.2.1.post0)
grpcio (1.17.1)
h5py (2.9.0)
html5lib (0.9999999)
httplib2 (0.9.2)
hyperlink (17.3.1)
idna (2.6)
incremental (16.10.1)
Jinja2 (2.10)
jsonpatch (1.16)
jsonpointer (1.10)
jsonschema (2.6.0)
Keras (1.2.2)
Keras-Applications (1.0.6)
Keras-Preprocessing (1.0.5)
language-selector (0.1)
Markdown (3.0.1)
MarkupSafe (1.0)
numpy (1.15.4)
oauthlib (2.0.6)
PAM (0.4.2)
Pillow (5.4.1)
pip (9.0.1)
protobuf (3.6.1)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pydot-ng (2.0.0)
pygobject (3.26.1)
PyJWT (1.5.3)
pyOpenSSL (17.5.0)
pyparsing (2.3.0)
pyserial (3.4)
python-apt (1.6.2)
python-debian (0.1.32)
PyYAML (3.13)
requests (2.18.4)
requests-unixsocket (0.1.5)
scipy (1.2.0)
service-identity (16.0.0)
setuptools (40.6.3)
six (1.12.0)
ssh-import-id (5.7)
systemd-python (234)
tensorboard (1.12.2)
tensorflow (1.5.0)
tensorflow-tensorboard (1.5.1)
termcolor (1.1.0)
Theano (1.0.3)
Twisted (17.9.0)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.22)
Werkzeug (0.14.1)
wheel (0.32.3)
zope.interface (4.3.2)

I have attached cfg file for your reference. The weights file is too large for uploading here.
[tiny-yolo-voc (2).zip](https://github.com/sw6y15/HKEvent/files/2752876/tiny-yolo-voc.2.zip)

Thank you very much.

**Comment by sw6y15** [comment]
Could you provide the WSL logs after you pip/pip3 install Keras==1.2.2?
In your previous screenshots, the error is due to Keras 2.x has changed **merge()** function. I thought that it could not be the same error as before.

![image](https://user-images.githubusercontent.com/29120664/51084612-d7bbf300-1767-11e9-945f-869c460d6571.png)

**Comment by jhl8041** [comment]
Sorry there were some changes in log.

**This is the most recent log:**

![image](https://user-images.githubusercontent.com/39699436/51084837-75fd8800-176b-11e9-916e-752b9815d008.png)

**Comment by sw6y15** [comment]
Well, for converting the yolo cfg weights, I think you should modfiy line 82 in **yad2k.py** located at YOLO-CoreML-MPSNNGraph/Convert/yad2k/
![image](https://user-images.githubusercontent.com/29120664/51085464-b9102900-1774-11e9-9818-9b60ee5b5046.png)
to
 weights_header = np.ndarray(
        shape=(4, ), dtype='int32', buffer=weights_file.read(**16**))
But if convert tiny yolo, I think it need not to change.
You can refer to [this](https://github.com/allanzelener/YAD2K/issues/104#issue-296280009)

**Comment by jhl8041** [comment]
![image](https://user-images.githubusercontent.com/39699436/51087212-16af7000-178b-11e9-9992-67915523765f.png)

This is what I still get after changing line 82 **buffer=weights_file.read(20)** to **buffer=weights_file.read(16)**

and I am sure I am using tiny yolo because the name of the weights file and cfg is both **tiny-yolo-voc.cfg tiny-yolo-voc.weights**
