### ISSUE TITLE
Could I replace anchors parameter in tiny-yolo-voc.cfg?

### ISSUE THREAD

**Issue by haoboluo** [sw6y15/HKEvent#6]
Area:
AI

Problem Session:
anchors parameter

Description:
I replace the "anchors" parameter in the tiny-yolo-voc.cfg by the result of `darknet.exe detector calc_anchors`. After training, replace the "anchors" parameter in the ObjectDetection.cs of UWPSampleCode. 
Are this two steps right? Please refer to the screenshots. 
And the calculated anchors are much different from default values in the tiny-yolo-voc.cfg. Is that related to the pixel intensity of fruit image?

Screenshots:
![image](https://user-images.githubusercontent.com/44913369/51121612-cbf92b00-1852-11e9-8663-477820f70815.png)

![image](https://user-images.githubusercontent.com/44913369/51121634-d87d8380-1852-11e9-8c2a-26ef5955f27d.png)

![image](https://user-images.githubusercontent.com/44913369/51121668-ee8b4400-1852-11e9-876a-16eee65c85be.png)

**Comment by jhl8041** [comment]
I have the same concern, when running `darknet.exe detector calc_anchors`, output value seems very large compared to the default value for voc.

**Comment by sw6y15** [comment]
Yep. **calc_anchors** uses k-mean method to cluster bounding box in your training data. For more strategies, you can refer to [Link](https://github.com/AlexeyAB/darknet#how-to-improve-object-detection)

**Comment by jhl8041** [comment]
> Yep. calc_anchors uses k-mean method to cluster bounding box in your training data. For more strategies, you can refer to Link

So does that 'Yep' mean the calculated output anchor value by `darknet.exe detector calc_anchors` is correct to replace this?
```
[region]
anchors = 1.08,1.19,  3.42,4.41,  6.63,11.38,  9.42,5.11,  16.62,10.52
```
or is there another calculation need to input values here?

**Comment by sw6y15** [comment]
It's correct step. Replace the anchors calculate from calc_anchors.
