### ISSUE TITLE
How to speed up training speed (already in GPU)?

### ISSUE THREAD

**Issue by haoboluo** [sw6y15/HKEvent#7]
Area:
AI

Problem Session:
GPU doesn't perform well.

Description:
I use surface book 2 to train the model and its GPU should be NVIDIA® GeForce® GTX 1060 discrete GPU w/6GB GDDR5 graphics memory. I installed CUDA 9.1 and cuDNN v7.0.5. I changed the "subdivisions" to be 32 because of `cuda out of memory`. The input fruit images are about 600. 
Please refer to the screenshots, we consumed 20 hours to reach 5861 iterations. 
Can I finish training within 24 hours  by tuning the Learning rate and steps? 
Or is there any wrong configuration about GPU which will slow down the training speed?
Screenshots (optional):
![image](https://user-images.githubusercontent.com/44913369/51122374-ac630200-1854-11e9-9c5f-735e0e40030e.png)

![image](https://user-images.githubusercontent.com/44913369/51121845-5fcaf700-1853-11e9-87a9-f67087cdbdf4.png)

**Comment by sw6y15** [comment]
You could try **subdivision = 16** if not out of memory. I think if your training images are tag well,  it needs time to converge. When your loss graph seems to converge with the Loss you are not satisfied, you can stop it and modify your training images and continue training by using the last saved weights. 

**darknet.exe detector train data/obj.data cfg/tiny-yolo-voc.cfg your_last_weights**

For more strategies refer to [Link](https://github.com/AlexeyAB/darknet#how-to-improve-object-detection)

**Comment by haoboluo** [comment]
> You could try **subdivision = 16** if not out of memory. I think if your training images are tag well, it needs time to converge. When your loss graph seems to converge with the Loss you are not satisfied, you can stop it and modify your training images and continue training by using the last saved weights.
> 
> **darknet.exe detector train data/obj.data cfg/tiny-yolo-voc.cfg your_last_weights**
> 
> For more strategies refer to [Link](https://github.com/AlexeyAB/darknet#how-to-improve-object-detection)

Thank you for reply! I have a test of  **subdivision = 16** and it's out of memory. 
Your Link is useful for me, thank you.
