### ISSUE TITLE
Visual Studio error on my own computer.

### ISSUE THREAD

**Issue by AK51** [sw6y15/HKEvent#8]
I tried to follow the doc in S4 to setup my own computer. But I got error when I tried to build the S2.
1. Follow a doc in S4 to install the Visual Studio
2. open the sln
3. change the hardware selection to x86
4. change the url and key in tag file
5. build
6. It has error, I clean the build and rebuild again, same error... Pls help.

I looked into the output, here is the error
...
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\UWPSampleCode.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'
1>CSC : error CS2001: Source file 'D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\obj\x86\Debug\App.g.i.cs' could not be found.
1>CSC : error CS2001: Source file 'D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\obj\x86\Debug\Controls\NotifyPopup.g.i.cs' could not be found.

**Comment by AK51** [comment]
Here are the two errors.
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\obj\x86\Debug\Controls\NotifyPopup.g.i.cs' could not be found.	UWPSampleCode	D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\CSC	1	Active
Error	CS2001	Source file 'D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\obj\x86\Debug\App.g.i.cs' could not be found.	UWPSampleCode	D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\CSC	1	Active

**Comment by LiangJy123** [comment]
## 1.clean your solution
![image](https://user-images.githubusercontent.com/13048899/51156405-6a6aa800-18b6-11e9-84af-009aa538a01d.png)
## 2.nuget  the "system.runtime" and install it.
![image](https://user-images.githubusercontent.com/13048899/51156439-8bcb9400-18b6-11e9-9f2f-68f51036c82e.png)
![image](https://user-images.githubusercontent.com/13048899/51156462-ad2c8000-18b6-11e9-8ebe-04fdd5645199.png)
## 3.rebuild your solution.
![image](https://user-images.githubusercontent.com/13048899/51156512-e107a580-18b6-11e9-94bb-4bf0ec89ff7c.png)

## make sure your Win10 is 1809  or newer,
![image](https://user-images.githubusercontent.com/13048899/51156657-87ec4180-18b7-11e9-986f-43202dfe4a18.png)
## and you are using the 17763 SDK in your solution.
![image](https://user-images.githubusercontent.com/13048899/51156595-4b204a80-18b7-11e9-808b-547a865ad0a7.png)

**Comment by AK51** [comment]
I have tried to repair, uninstall/reinstall Visual Studio before. No luck so far.

**Comment by AK51** [comment]
I am working on your solution. I am using Win10 home. Where can I see your window? Control Panel/System? Thx
For the last picture, I am trying to find the way to click and open your window... sorry about that.

**Comment by AK51** [comment]
I did the rest except looking for my own win 10 home version. After I built it, I got new error

Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot assign text value '0:0:0' into property 'BeginTime' of type 'Nullable'	UWPSampleCode	D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml	16	
Error		A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.	UWPSampleCode	D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml	17

**Comment by AK51** [comment]
Here is the Output,

…

1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3106: Assembly strong name "C:\Users\85268\.nuget\packages\microsoft.netcore.universalwindowsplatform\6.1.9\ref\uap10.0.15138\netstandard.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3106: Assembly strong name "C:\Users\85268\.nuget\packages\newtonsoft.json\12.0.1\lib\netstandard2.0\Newtonsoft.Json.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(16,33): XamlCompiler error WMC0055: Cannot assign text value '0:0:0' into property 'BeginTime' of type 'Nullable'
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(17,40): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(18,40): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(25,28): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(26,28): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(28,109): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(28,123): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\MainPage.xaml(38,71): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by AK51** [comment]
Found my window home 10 version
Version 1803 only. I bought this new computer in Sept/2018
How to upgrade it?

**Comment by AK51** [comment]
Updating the version....

**Comment by AK51** [comment]
After the updated.
And then clean up + rebuild, I got these errors...

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)	UWPSampleCode	D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\AI\ComputerVisionTag.cs	1	Active
Error	CS0234	The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)	UWPSampleCode	D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\AI\ComputerVisionTag.cs	4	Active
Error	CS0234	The type or namespace name 'Net' does not exist in the namespace 'System' (are you missing an assembly reference?)	UWPSampleCode	D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\AI\ComputerVisionTag.cs	5	Active
Error	CS0234	The type or namespace name 'Net' does not exist in the namespace 'System' (are you missing an assembly reference?)	UWPSampleCode	D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\AI\ComputerVisionTag.cs	6	Active
…

OUTPUT
…
1>D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3106: Assembly strong name "C:\Users\85268\.nuget\packages\newtonsoft.json\12.0.1\lib\netstandard2.0\Newtonsoft.Json.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(16,33): XamlCompiler error WMC0055: Cannot assign text value '0:0:0' into property 'BeginTime' of type 'Nullable'
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(17,40): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(18,40): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(25,28): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(26,28): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(28,109): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\Controls\NotifyPopup.xaml(28,123): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
1>D:\Document\win_drone_workshop\OneDrive_2019-01-11\Joint Universities AI Workshop\DroneXAI_final\S2-HowToUseMicrosoftCognitiveService\UWPSampleCode_Session2\UWPSampleCode\MainPage.xaml(38,71): XamlCompiler error WMC0003: A type's assembly could not be resolved.  This is often because it was forwarded to an unresolved assembly: Type universe cannot resolve assembly: System.Runtime.WindowsRuntime.UI.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by AK51** [comment]
![image](https://user-images.githubusercontent.com/8468724/51159993-c9381d80-18c6-11e9-9071-a89cd36a1c97.png)
![image](https://user-images.githubusercontent.com/8468724/51160004-d6550c80-18c6-11e9-8aa3-61dc4fc0b557.png)
![image](https://user-images.githubusercontent.com/8468724/51160015-e66cec00-18c6-11e9-9366-dc304f378a6a.png)
![image](https://user-images.githubusercontent.com/8468724/51160029-f1278100-18c6-11e9-980c-f60123c6f060.png)
![image](https://user-images.githubusercontent.com/8468724/51160051-08666e80-18c7-11e9-85d5-fcf8b140df19.png)

**Comment by AK51** [comment]
I unzip a new project and run the S2 again. I couldn't even install the System.Runtime…
![image](https://user-images.githubusercontent.com/8468724/51160172-b96d0900-18c7-11e9-8540-9f5b77647fd7.png)

**Comment by LiangJy123** [comment]
In my computer ，I change the platform to x86 and  then rebuild the solution successfully.So I think the issues  is a matter of the environment.
## I think you can run the "visual studio installer.exe" .
![image](https://user-images.githubusercontent.com/13048899/51161565-e0c6d480-18cd-11e9-9338-803c3d9d49f9.png)
## make sure the some items are checked
![image](https://user-images.githubusercontent.com/13048899/51161663-49ae4c80-18ce-11e9-9e5e-00e2e1935192.png)

![image](https://user-images.githubusercontent.com/13048899/51161706-7bbfae80-18ce-11e9-9ceb-debc463951c9.png)

![image](https://user-images.githubusercontent.com/13048899/51161737-9560f600-18ce-11e9-8e9b-0e5dc2d10441.png)

**Comment by AK51** [comment]
Still not working....
![image](https://user-images.githubusercontent.com/8468724/51162419-0dc8b680-18d1-11e9-8a4b-3f485e1c08d1.png)
![image](https://user-images.githubusercontent.com/8468724/51162434-1d47ff80-18d1-11e9-8d47-4e753a95761c.png)

**Comment by AK51** [comment]
I saw your installer does not have the desktop, I uninstalled the Desktop too. But the error is still there. :<

**Comment by AK51** [comment]
I did uninstall the Visual Studio before, is there anywhere I should clean up before I reinstall again? Thx

**Comment by LiangJy123** [comment]
OK. i think it doesn't matter that you uninstalled it before. So can you rebuild the solution and show me the output again? because there are so many picture and information that  i can't find the lastest one .

**Comment by AK51** [comment]
![image](https://user-images.githubusercontent.com/8468724/51163420-8d0bb980-18d4-11e9-9c39-a201cace9a8c.png)

![image](https://user-images.githubusercontent.com/8468724/51163444-98f77b80-18d4-11e9-88a8-f4039627bf16.png)

![image](https://user-images.githubusercontent.com/8468724/51163457-a6ad0100-18d4-11e9-9384-6c436e9eb764.png)

![image](https://user-images.githubusercontent.com/8468724/51163473-b62c4a00-18d4-11e9-81ad-b81cdb6522ca.png)

**Comment by AK51** [comment]
If I unzip a new S2 project and try again, I can't install System.Runtime.
![image](https://user-images.githubusercontent.com/8468724/51163526-fc81a900-18d4-11e9-8a08-63f43d583e91.png)

![image](https://user-images.githubusercontent.com/8468724/51163529-02778a00-18d5-11e9-9e2c-85bcf8ecc0f1.png)

**Comment by AK51** [comment]
If necessary, please show me the capture screen of what I need to install. I can uninstall everything and reinstall again. Thx.

**Comment by LiangJy123** [comment]
OK, forget the System.Runtime . i have no ideas about your problems. Let's  try to nuget the System.Runtime.WindowsRuntime.UI.Xaml ,because i see it at the output list.

**Comment by AK51** [comment]
![image](https://user-images.githubusercontent.com/8468724/51164076-b9c0d080-18d6-11e9-8c78-533d033c2408.png)

![image](https://user-images.githubusercontent.com/8468724/51164096-c6ddbf80-18d6-11e9-90dc-9232ccef58a5.png)

**Comment by LiangJy123** [comment]
##### Allright, maybe some some references can be "lost".Try to delete the reference and add it again.
![image](https://user-images.githubusercontent.com/13048899/51168953-a0735080-18e5-11e9-95c5-1a0e736feb59.png)

**Comment by AK51** [comment]
Mmm… I uninstall everything first. Thx

**Comment by AK51** [comment]
I have uninstalled the VC
Restart the computer
Then, reinstall VC.... still in progress

![image](https://user-images.githubusercontent.com/8468724/51171033-c64f2400-18ea-11e9-82b3-ff7b500d11bd.png)
![image](https://user-images.githubusercontent.com/8468724/51171055-d109b900-18ea-11e9-9b80-c4ae5a40d441.png)

**Comment by AK51** [comment]
Same problem after reinstall the VC. :< Is it the problem of my HP OMEN?
![image](https://user-images.githubusercontent.com/8468724/51172417-2abfb280-18ee-11e9-8186-8b22329b748b.png)
![image](https://user-images.githubusercontent.com/8468724/51172451-3ad79200-18ee-11e9-9343-0f8c8c335dc0.png)

**Comment by AK51** [comment]
And I deleted the .vs folder and rebuild it too. Same problem...

**Comment by sw6y15** [comment]
Can you try to build pass [this DJI sample code](https://github.com/dji-sdk/Windows-SDK) follow get started.

**Comment by AK51** [comment]
Several errors when I run the DJI sample code. I did solved some of them up to this point.
I think my computer has some residue Visual Studio setting somewhere. Anyway, thanks for your help. I may find another computer and try the code later. Thx.

![image](https://user-images.githubusercontent.com/8468724/51224734-470d2f00-1982-11e9-835f-652a718b62d9.png)
