### ISSUE TITLE
About recalculating anchor value

### ISSUE THREAD

**Issue by jhl8041** [sw6y15/HKEvent#9]
The avg loss is converging but I am not satisfied with the current avg loss.

Would recalculating anchor value after adding more tags and continue with previous weight help reduce the avg loss rate? or is it better to keep anchor value the same even if I add more data to the previous data?

And is there other ways to reduce the avg loss?

Thank you very much.

**Comment by sw6y15** [comment]
Anchor indicates the distribution of your training bounding box shape and size. If you add training data with similar w-h ratio and box size as before, it will just change the anchor value a little bit. To improve your object detection, you can refer to those [methods](https://github.com/AlexeyAB/darknet#how-to-improve-object-detection)
